spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis