spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home-automation
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis